import { OpenAIAnalysis } from "../models/Analysis.js";

export const getDefaultAnalysis = (url: string): OpenAIAnalysis => ({
	url,
	purpose: "Не удалось определить",
	primary_content_type: "Не удалось определить",
	mobile_optimization: { score: 0, status: "Не удалось определить" },
	average_loading_speed: { milliseconds: 0, notes: "Не удалось определить" },
	ssl_certificate: { status: "Не удалось определить", security_measures: "Не удалось определить" },
	seo_score: {
		score: 0,
		keywords: "Не удалось определить",
		meta_tags: "Не удалось определить",
		description: "Не удалось определить",
		structure: "Не удалось определить",
	},
	links: { internal_links: 0, external_links: 0 },
	accessibility: {
		score: 0,
		alt_tags: "Не удалось определить",
		aria_labels: "Не удалось определить",
		keyboard_navigation: "Не удалось определить",
	},
	bounce_rate: { percentage: 0, reason: "Не удалось определить" },
	traffic_distribution: { direct: 0, social: 0, referral: 0, organic: 0, paid: 0 },
	traffic_geography: { russia: 0, usa: 0, europe: 0, asia: 0, other: 0 },
	traffic_trends: { growth_percentage: 0, notes: "Не удалось определить" },
	traffic_seasonality: "Не удалось определить",
	performance_scores: { mobile: 0, desktop: 0 },
	quality_of_content: { uniqueness: "Не удалось определить", relevance: "Не удалось определить" },
	domain_authority: 0,
	user_engagement_metrics: {
		average_time_on_site: 0,
		page_views_per_session: 0,
		conversion_rate: 0,
		user_paths: "Не удалось определить",
	},
	device_distribution: { mobile: 0, desktop: 0, tablet: 0 },
	backlinks: { quantity: 0, quality: "Не удалось определить" },
	content_freshness: "Не удалось определить",
	security_vulnerabilities: { xss: "Не удалось определить", csrf: "Не удалось определить" },
	tech_stack: "Не удалось определить",
	page_size: { kilobytes: 0, notes: "Не удалось определить" },
	competitors: "Не удалось определить",
	market_share: 0,
	social_mentions: 0,
	domain_age: 0,
	server_response_time: { milliseconds: 0, notes: "Не удалось определить" },
	recommendations: {
		performance: "Не удалось определить",
		seo: "Не удалось определить",
		accessibility: "Не удалось определить",
		security: "Не удалось определить",
		content_quality: "Не удалось определить",
		traffic: "Не удалось определить",
	},
});